In [35]:
%matplotlib inline
import numpy as np
import pandas as pd
import scipy
import sklearn
import matplotlib.pyplot as plt
import seaborn as sns

In [36]:
# Grab and process the raw data.

data_raw = pd.read_csv ('amazon_cells_labelled.txt', sep='\t')


In [37]:
data_raw.head ()
data_raw.columns = ['review', 'sentiment']

keywords = ['good', 'great']

for key in keywords:
    # Note that we add spaces around the key so that we're getting the word,
    # not just pattern matching.
    data_raw[str(key)] = data_raw.review.str.contains(
         str(key),
        case=False
    )

In [38]:
data_raw.head ()

review  sentiment   good  great
0                        Good case, Excellent value.          1   True  False
1                             Great for the jawbone.          1  False   True
2  Tied to charger for conversations lasting more...          0  False  False
3                                  The mic is great.          1  False   True
4  I have to jiggle the plug to get it to line up...          0  False  False

In [39]:
data_raw['data_raw_new'] = (data_raw['review'] == 'keyword')


In [40]:
data = data_raw[keywords]
target = data_raw['sentiment']

In [41]:
# Our data is binary / boolean, so we're importing the Bernoulli classifier.
from sklearn.naive_bayes import BernoulliNB

# Instantiate our model and store it in a new variable.
bnb = BernoulliNB()

# Fit our model to the data.
bnb.fit(data, target)

#before this line is me training the model
#now that i have a trained model i can fun predictions below:

# Classify, storing the result in a new variable.
y_pred = bnb.predict(data)

#if i had split data into training and test sets i would FIT with the training data and in this step i would use the test data) 


# Display our results.
print("Number of mislabeled points out of a total {} points : {}".format(
    data.shape[0],
    (target != y_pred).sum()
))

Number of mislabeled points out of a total 999 points : 369


In [42]:
data_raw.head ()


review  sentiment   good  great  \
0                        Good case, Excellent value.          1   True  False   
1                             Great for the jawbone.          1  False   True   
2  Tied to charger for conversations lasting more...          0  False  False   
3                                  The mic is great.          1  False   True   
4  I have to jiggle the plug to get it to line up...          0  False  False   

   data_raw_new  
0         False  
1         False  
2         False  
3         False  
4         False

In [43]:
data_raw.info ()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 999 entries, 0 to 998
Data columns (total 5 columns):
review          999 non-null object
sentiment       999 non-null int64
good            999 non-null bool
great           999 non-null bool
data_raw_new    999 non-null bool
dtypes: bool(3), int64(1), object(1)
memory usage: 18.6+ KB


In [44]:
from sklearn.metrics import confusion_matrix
confusion_matrix(target, y_pred)

array([[480,  19],
       [350, 150]])

In [45]:
#look up documentation for bernoulliNB

from sklearn.model_selection import cross_val_score
cross_val_score(bnb, data, target, cv=10)

array([0.66      , 0.68      , 0.68      , 0.66      , 0.6       ,
       0.66      , 0.58      , 0.58      , 0.64      , 0.56565657])

In [46]:

from sklearn.naive_bayes import BernoulliNB
bnb = BernoulliNB()
y_pred = bnb.fit(data, target).predict(data)

In [51]:
%matplotlib inline
import numpy as np
import pandas as pd
import scipy
import sklearn
import matplotlib.pyplot as plt
import seaborn as sns

# Grab and process the raw data.

data_raw = pd.read_csv ('amazon_cells_labelled.txt', sep='\t')


In [52]:
data_raw.head ()
data_raw.columns = ['review', 'sentiment']

keywords = ['good', 'great', 'excellent']

for key in keywords:
    # Note that we add spaces around the key so that we're getting the word,
    # not just pattern matching.
    data_raw[str(key)] = data_raw.review.str.contains(
         str(key),
        case=False
    )

In [32]:
data_raw.head ()

review  sentiment   good  great  \
0                        Good case, Excellent value.          1   True  False   
1                             Great for the jawbone.          1  False   True   
2  Tied to charger for conversations lasting more...          0  False  False   
3                                  The mic is great.          1  False   True   
4  I have to jiggle the plug to get it to line up...          0  False  False   

   excellent  
0       True  
1      False  
2      False  
3      False  
4      False

In [53]:
data_raw['data_raw_new'] = (data_raw['review'] == 'keyword')


In [54]:
data = data_raw[keywords]
target = data_raw['sentiment']

In [55]:
# Our data is binary / boolean, so we're importing the Bernoulli classifier.
from sklearn.naive_bayes import BernoulliNB

# Instantiate our model and store it in a new variable.
bnb = BernoulliNB()

# Fit our model to the data.
bnb.fit(data, target)

#before this line is me training the model
#now that i have a trained model i can fun predictions below:

# Classify, storing the result in a new variable.
y_pred = bnb.predict(data)

#if i had split data into training and test sets i would FIT with the training data and in this step i would use the test data) 


# Display our results.
print("Number of mislabeled points out of a total {} points : {}".format(
    data.shape[0],
    (target != y_pred).sum()
))

Number of mislabeled points out of a total 999 points : 346


In [56]:
from sklearn.model_selection import cross_val_score
cross_val_score(bnb, data, target, cv=10)

array([0.68      , 0.7       , 0.7       , 0.69      , 0.63      ,
       0.67      , 0.6       , 0.6       , 0.68      , 0.58585859])

In [59]:
%matplotlib inline
import numpy as np
import pandas as pd
import scipy
import sklearn
import matplotlib.pyplot as plt
import seaborn as sns

# Grab and process the raw data.

data_raw = pd.read_csv ('amazon_cells_labelled.txt', sep='\t')


In [60]:
data_raw.head ()
data_raw.columns = ['review', 'sentiment']

keywords = ['good', 'great', 'excellent', 'value']

for key in keywords:
    # Note that we add spaces around the key so that we're getting the word,
    # not just pattern matching.
    data_raw[str(key)] = data_raw.review.str.contains(
         str(key),
        case=False
    )

In [61]:
data_raw.head ()

review  sentiment   good  great  \
0                        Good case, Excellent value.          1   True  False   
1                             Great for the jawbone.          1  False   True   
2  Tied to charger for conversations lasting more...          0  False  False   
3                                  The mic is great.          1  False   True   
4  I have to jiggle the plug to get it to line up...          0  False  False   

   excellent  value  
0       True   True  
1      False  False  
2      False  False  
3      False  False  
4      False  False

In [62]:
data_raw['data_raw_new'] = (data_raw['review'] == 'keyword')
data = data_raw[keywords]
target = data_raw['sentiment']

# Our data is binary / boolean, so we're importing the Bernoulli classifier.
from sklearn.naive_bayes import BernoulliNB

# Instantiate our model and store it in a new variable.
bnb = BernoulliNB()

# Fit our model to the data.
bnb.fit(data, target)

#before this line is me training the model
#now that i have a trained model i can fun predictions below:

# Classify, storing the result in a new variable.
y_pred = bnb.predict(data)

#if i had split data into training and test sets i would FIT with the training data and in this step i would use the test data) 


# Display our results.
print("Number of mislabeled points out of a total {} points : {}".format(
    data.shape[0],
    (target != y_pred).sum()
))

Number of mislabeled points out of a total 999 points : 345


In [63]:
from sklearn.model_selection import cross_val_score
cross_val_score(bnb, data, target, cv=10)

array([0.68      , 0.7       , 0.7       , 0.69      , 0.64      ,
       0.67      , 0.6       , 0.6       , 0.68      , 0.58585859])